### ISSUE TITLE
The requirement of source while using RPC

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-client-zenoh-rust#3]
Hi @PLeVasseur and @stevenhartley 

Since we didn't have too much time to discuss the topic yesterday, it might be clearer to create an independent issue about this.
As far as I know, the requirement for needing "source" comes from how to route the response back to the sender.
However, I'm still a little confused about this. Let me list my questions to get us on the same page.

1. Why needs to know the "source"?
While using RPC, I think uProtocol application developers don't need to know how to send back the response.
It should be done by the UPClient and keep the upper layer agnostic.
Taking Zenoh as an example, the RPC client uses `get` to send a query, and the RPC server will trigger `queryable` callback and get the query.
https://github.com/ZettaScaleLabs/up-client-zenoh-rust/blob/5faef310caa0c5e2b3f6bcc4494720e418e194f0/src/lib.rs#L333
Then RPC Server can reply to the query directly.
https://github.com/ZettaScaleLabs/up-client-zenoh-rust/blob/5faef310caa0c5e2b3f6bcc4494720e418e194f0/src/lib.rs#L204
Zenoh takes over how to send back the response.

2. About the uStreamer implementation
The following architecture is what I imagine about how the implementation will do.
I guess we don't need to deal with UURI routing here, but I might miss something.
Maybe we can align about the implementation and see what the gap is.
![uStreamer architecture](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/assets/456210/b9f36a86-9321-4da0-9d5b-162e207f9a55)

3. The difference between UUID & UURI
Although I asked it yesterday, I'm still quite confused about it.
If every entity has its own UURI, why do we still need UUID?
![image](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/assets/456210/06af168d-5226-4e6e-af16-44c2976d3d1d)
I thought UUID is the identity of the entity while UURI is the topic, with which different entities can talk to each other.

4. How to assign UURI to the entity
If we assume every entity has its own UURI, then the question will be how users initialize their own UURI.
Let's take RPC client as an example and here is the example code
https://github.com/ZettaScaleLabs/up-client-zenoh-rust/blob/5faef310caa0c5e2b3f6bcc4494720e418e194f0/examples/rpc_client.rs#L31
Now we only declare the UURI which is registered by the server, but we don't have any API for clients to create its own UURI right now.

**Comment by stevenhartley** [comment]
@evshary all great questions, let me reply to each below.

There are a few things that fundamentally we wanted to preserve in uProtocol that is not just about making sure the response is passed back to the requester  or a message is published. We want to ensure that there is traceability across all the communication protocols so a message that is generated at step 1 and 6 of your diagram above is preserved both the payload and its corresponding header (UAttributes) across all transports to the destination. Regeneration of header means it is a new message and we loose traceability and knowledge of the original creator of said message. 

1. Will be answered in 2 below
2. In addition to the description above, the issue is at step 7 & 8 of your picture, send() needs to pass UUri (who sent it), UPayload, and UAttributes. If I don't have the source from the request, the "other protocol RpcServer" won't know who to send the request to (what to put in UAttributes.sink). Additionally, if there is another streamer after 9, it won't be able forward the event as well over another transport, we need the source/sink.
3. UUID is a message (publish, request, response) unique identifier that includes the timestamp and instance id (that changes each time the uE is created). UUri is an address to locate the running uE, they serve very unique purposes. 
4. UEntity information is set in their proto definitions. One day we'll need a IANA registry but for now we are defining them in COVESA/uservices and in up-core-api. Vendor specific will just have to make sure they don't clash in the namespace (i.e. call their ue gm.hartleyApp vs vw.TomApp) and ensure the IDs are also not overlapping (we could reserve ranges but we'll cross that bridge when we get there). From the proto generated code, we can build UEntity and UResource portions of the URI, the UAuthority should be empty for local communication and then filled with the device name/address when it is deployed (and can be fetched from some deployment specific interface).

**Comment by evshary** [comment]
@stevenhartley Thanks for your detailed responses!
It's fine for me to add source UUri while sending the request. I just want to check whether I misunderstood the design and avoid the wrong implementation.

> 1. Will be answered in 2 below
> 2. In addition to the description above, the issue is at step 7 & 8 of your picture, send() needs to pass UUri (who sent it), UPayload, and UAttributes. If I don't have the source from the request, the "other protocol RpcServer" won't know who to send the request to (what to put in UAttributes.sink). Additionally, if there is another streamer after 9, it won't be able forward the event as well over another transport, we need the source/sink.

I thought it's not difficult for other protocol RpcServer to know how to send back the response if they have a request and response mechanism similar to queryable in Zenoh. The protocol should tackle this. But maybe uProtocol doesn't have this assumption and reserves the "source address" for the protocol (w/o req&resp) to know how to route back the response.

> 3. UUID is a message (publish, request, response) unique identifier that includes the timestamp and instance id (that changes each time the uE is created). UUri is an address to locate the running uE, they serve very unique purposes.

That's clear to me now. UUID is used to identify different messages while UUri is used to identify and locate uE.

> 4. UEntity information is set in their proto definitions. One day we'll need a IANA registry but for now we are defining them in COVESA/uservices and in up-core-api. Vendor specific will just have to make sure they don't clash in the namespace (i.e. call their ue gm.hartleyApp vs vw.TomApp) and ensure the IDs are also not overlapping (we could reserve ranges but we'll cross that bridge when we get there). From the proto generated code, we can build UEntity and UResource portions of the URI, the UAuthority should be empty for local communication and then filled with the device name/address when it is deployed (and can be fetched from some deployment specific interface).

Maybe my question is how the application using uProtocol attaches its own UURI. Taking a specific example, while we are sending an RPC request, the current uProtocol API does not support appending its own UUri. I guess we need to make some modifications to the API.

**Comment by evshary** [comment]
I think this can be closed now.
